---
# Homepage configuration
# See http://fontawesome.com/icons for icons options

title: "Mediabox"
subtitle: "thishost"
icon: "far fa-play-circle" # Optional icon

header: true
footer: false
columns: "4"
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

links:
  - name: "Mediabox"
    icon: "fab fa-github"
    url: "https://github.com/midyear66/mediabox"
    target: "_blank"
  - name: "Buy me a coffee"
    icon: "fas fa-mug-hot"
    url: "https://cash.app/$TomMorgan"
    target: "_blank"
  - name: "Getting Started"
    icon: "fas fas fa-check-square"
    url: "/assets/mediaboxconfig.html"
    target: "_blank"
  - name: "Port Mappings"
    icon: "fas fa-network-wired"
    url: "/assets/portmap.html"
    target: "_blank"

# Services
# First level array represent a group.
services:
  - name: "Get It"
    icon: "fas fa-download"
    items:
      - name: "Deluge"
        logo: "assets/icons/deluge.png"
        tag: "get"
        tagstyle: "is -info"
        url: "http://locip:8112"
        target: "_blank"
      - name: "NZBGet"
        logo: "assets/icons/nzbget.png"
        tag: "get"
        tagstyle: "is -info"
        url: "http://locip:6789"
        target: "_blank"
      - name: "Ombi"
        logo: "assets/icons/ombi.png"
        tag: "get"
        tagstyle: "is -info"
        url: "http://locip:3579"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/icons/prowlarr.png"
        tag: "get"
        tagstyle: "is -info"
        url: "http://locip:9696"
        target: "_blank"
  - name: "Manage It"
    icon: "fas fa-edit"
    items:
      - name: "Lidarr"
        logo: "assets/icons/lidarr.png"
        tag: "manage"
        tagstyle: "is-info"
        url: "http://locip:8686"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/icons/radarr.png"
        tag: "manage"
        tagstyle: "is-info"
        url: "http://locip:7878"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/icons/sonarr.png"
        tag: "manage"
        tagstyle: "is-info"
        url: "http://locip:8989"
        target: "_blank"
  - name: "Monitor It"
    icon: "fas fa-heartbeat"
    items:
      - name: "Portainer"
        logo: "assets/icons/portainer.png"
        tag: "monitor"
        tagstyle: "is-danger"
        url: "https://locip:9443"
        target: "_blank"
      - name: "Maintainerr"
        logo: "assets/icons/maintainerr.png"
        tag: "monitor"
        tagstyle: "is-danger"
        url: "http://locip:6246"
        target: "_blank"
      - name: "Tautulli"
        logo: "assets/icons/tautulli.png"
        tag: "monitor"
        tagstyle: "is-danger"
        url: "http://locip:8181"
        target: "_blank"
  - name: "Watch It"
    icon: "fas fa-tv"
    items:
      - name: "Plex"
        logo: "assets/icons/plex.png"
        tag: "watch"
        tagstyle: "is-success"
        url: "http://plexip:32400/web"
        target: "_blank"
